### ISSUE TITLE
Demo asparagus.html not working under IE

### ISSUE THREAD

**Issue by tkrotoff** [Form5/parallax#1]
Tested under IE11

It is because you use [window.scrollY](https://github.com/Form5/parallax/blob/master/demo3/asparagus.js#L48) instead of [window.pageYOffset](https://developer.mozilla.org/en-US/docs/Web/API/Window.scrollY)
scrollY and pageYOffset are identical except pageYOffset is supported by all browsers including IE.

**Comment by benediktvaldez** [comment]
@tkrotoff Ah, good catch, fixed now!

:+1:

**Comment by razvanphp** [comment]
Your demo site still uses the old code, so not working in IE. You can update it or link directly to the repo:

http://htmlpreview.github.io/?https://raw.githubusercontent.com/Form5/parallax/master/demo3/asparagus.html
